### ISSUE TITLE
Errors with dependencies and missing Dockerfile

### ISSUE THREAD

**Issue by manuman94** [DenzelCode/nest-angular-auth-client#3]
Hey there! Thanks for providing such a nice boilerplate for authentication powered applications. I find it so useful!

I cloned the project and using `npm start` works very well! But when tried to deploy it in a Docker container I faced some issues. This is the Dockerfile I created:

```
FROM node:latest

ENV PORT=8080

WORKDIR /app
COPY package.json /app/
RUN yarn
COPY . /app/
CMD ["yarn", "run", "start:worker"]
EXPOSE ${PORT}
```

I know that maybe is not the best practice use `http-server` for production, but I'm only trying to make this project work altogether with the API (which I got working in a Docker container too). Plus, the issue comes in the Angular build step, so this is not related.

At the `ng build` step I get this error:

```
2023-01-28T23:19:25.690058500Z node:internal/crypto/hash:71
2023-01-28T23:19:25.690103100Z this[kHandle] = new _Hash(algorithm, xofLen);
2023-01-28T23:19:25.690108100Z ^
2023-01-28T23:19:25.690110900Z
2023-01-28T23:19:25.690113500Z Error: error:0308010C:digital envelope routines::unsupported
2023-01-28T23:19:25.690116400Z at new Hash (node:internal/crypto/hash:71:19)
2023-01-28T23:19:25.690119000Z at Object.createHash (node:crypto:140:10)
2023-01-28T23:19:25.690121600Z at BulkUpdateDecorator.hashFactory (/app/node_modules/webpack/lib/util/createHash.js:145:18)
2023-01-28T23:19:25.690124400Z at BulkUpdateDecorator.update (/app/node_modules/webpack/lib/util/createHash.js:46:50)
2023-01-28T23:19:25.690127200Z at OriginalSource.updateHash (/app/node_modules/webpack/node_modules/webpack-sources/lib/OriginalSource.js:130:8)
2023-01-28T23:19:25.690129900Z at NormalModule._initBuildHash (/app/node_modules/webpack/lib/NormalModule.js:880:17)
2023-01-28T23:19:25.690132500Z at handleParseResult (/app/node_modules/webpack/lib/NormalModule.js:946:10)
2023-01-28T23:19:25.690135200Z at /app/node_modules/webpack/lib/NormalModule.js:1040:4
2023-01-28T23:19:25.690137800Z at processResult (/app/node_modules/webpack/lib/NormalModule.js:755:11)
2023-01-28T23:19:25.690140500Z at /app/node_modules/webpack/lib/NormalModule.js:819:5 {
2023-01-28T23:19:25.690143200Z opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
2023-01-28T23:19:25.690145800Z library: 'digital envelope routines',
2023-01-28T23:19:25.690148400Z reason: 'unsupported',
2023-01-28T23:19:25.690151000Z code: 'ERR_OSSL_EVP_UNSUPPORTED'
2023-01-28T23:19:25.690153600Z }
```

Could you help me creating a working Dockerfile?

Thanks!

**Comment by DenzelCode** [comment]
Hey @manuman94 !

Thank you for your kind words.

For this problem, I would recommend you create a Dockerfile building the project (npm run build), and then in another stage (https://docs.docker.com/build/building/multi-stage/) create an NGINX server and copy the files of the output of build into the public directory of the NGINX server.

I added a Dockerfile to the repo on commit https://github.com/DenzelCode/nest-angular-auth-client/commit/a4208ac73759717394757645e096122e97680149 hope you enjoy it!

**Comment by manuman94** [comment]
Thanks! It works perfectly! ;)
